# Generated by Django 5.0.3 on 2025-02-21 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('COM', 'Computer'), ('MON', 'Monitor'), ('PRT', 'Printer'), ('NET', 'Network Equipment'), ('SRV', 'Server'), ('PER', 'Peripheral'), ('SFT', 'Software'), ('OTH', 'Other')], max_length=3)),
                ('location', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
