# Generated by Django 5.1.6 on 2025-03-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('A/V', 'A/V Equipment'), ('COM', 'Computer'), ('MON', 'Monitor'), ('NET', 'Network Equipment'), ('PER', 'Peripheral'), ('PRT', 'Printer'), ('PRJ', 'Projector'), ('SRV', 'Server'), ('SFT', 'Software'), ('OTH', 'Other')], max_length=3),
        ),
    ]
