# Generated by Django 5.1.6 on 2025-03-14 18:24

import assets.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='bitlocker_key',
            field=models.CharField(blank=True, help_text='BitLocker recovery key for this device (48 digits, staff only)', max_length=100, null=True, validators=[assets.validators.validate_bitlocker_key]),
        ),
    ]
