# Generated by Django 5.0.3 on 2025-02-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='notify_approaching_sla',
            field=models.BooleanField(default=True, help_text='Send notifications when tickets are approaching SLA deadline'),
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_new_message',
            field=models.BooleanField(default=True, help_text='Send notifications for new messages'),
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_sla_breach',
            field=models.BooleanField(default=True, help_text='Send notifications when tickets breach SLA'),
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_status_changed',
            field=models.BooleanField(default=True, help_text='Send notifications when ticket status changes'),
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_ticket_assigned',
            field=models.BooleanField(default=True, help_text='Send notifications when tickets are assigned'),
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_ticket_created',
            field=models.BooleanField(default=True, help_text='Send notifications for new tickets'),
        ),
        migrations.AddField(
            model_name='settings',
            name='notify_ticket_resolved',
            field=models.BooleanField(default=True, help_text='Send notifications when tickets are resolved'),
        ),
    ]
