# Generated by Django 5.1.6 on 2025-02-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_settings_notify_approaching_sla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='smtp_from_email',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
