# Generated by Django 5.1.7 on 2026-01-06 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_settings_smtp_from_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='notify_ticket_created',
        ),
    ]
