# Generated by Django 5.0.3 on 2025-02-21 01:11

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(default=tickets.models.generate_ticket_number, max_length=20, unique=True)),
                ('access_code', models.CharField(default=tickets.models.generate_access_code, max_length=6)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('requestor_email', models.EmailField(max_length=254)),
                ('requestor_phone', models.CharField(blank=True, max_length=20)),
                ('requestor_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('INC', 'Incident'), ('MAJ', 'Major Incident'), ('REQ', 'Request')], max_length=3)),
                ('subtype', models.CharField(choices=[('NET', 'Network'), ('WRK', 'Laptop/Workstation'), ('SRV', 'Server'), ('PRT', 'Printer'), ('SFT', 'Software'), ('ACC', 'Account')], max_length=3)),
                ('item', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASG', 'Assigned'), ('PRG', 'In Progress'), ('WTG', 'Waiting for Response'), ('RES', 'Resolved'), ('CLS', 'Closed')], default='NEW', max_length=3)),
                ('has_new_responses', models.BooleanField(default=False)),
                ('assets', models.ManyToManyField(blank=True, to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ticket_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_from_requestor', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
        ),
    ]
