# Generated by Django 5.0.3 on 2025-02-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('INC', 'Incident'), ('REQ', 'Request')], max_length=3),
        ),
    ]
