# Generated by Django 5.1.6 on 2025-03-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='subtype',
            field=models.CharField(choices=[('ACC', 'Account'), ('LAB', 'Lab'), ('NET', 'Network'), ('WRK', 'Laptop/Workstation'), ('PRT', 'Printer'), ('SRV', 'Server'), ('SFT', 'Software')], max_length=3),
        ),
    ]
